language: r
cache: packages

apt_packages:
  # git2.h required by gert (probably dependency: testthat -> usethis)
  - libgit2-dev

r:
  - release
  - devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

env:
  - RUN_SLOW_TESTS=true
  - _R_CHECK_DEPENDS_ONLY=true
